// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import TypedJs1Controller from "./typed_js_1_controller"
application.register("typed-js-1", TypedJs1Controller)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
